// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnztsqcidldwchefjgyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhuenRzcWNpZGxkd2NoZWZqZ3l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5Nzg5NzQsImV4cCI6MjA2MTU1NDk3NH0.n-FV4PhVY14FW9vx8tdVBzwNXaHTWp64YmAUNm_87J0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);